// <auto-generated />
using System;
using FSH.Modules.Auditing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Starter.Migrations.PostgreSQL.Audit
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260525070333_Auditing_AddEntityColumns")]
    partial class AuditingAddEntityColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityOperation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<byte>("Severity")
                        .HasColumnType("smallint");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("SpanId")
                        .HasColumnType("text");

                    b.Property<long>("Tags")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditRecords_CorrelationId");

                    b.HasIndex("PayloadJson")
                        .HasDatabaseName("IX_AuditRecords_PayloadJson_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PayloadJson"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PayloadJson"), new[] { "jsonb_path_ops" });

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_AuditRecords_Source_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Source"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Source"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TraceId")
                        .HasDatabaseName("IX_AuditRecords_TraceId");

                    b.HasIndex("UserName")
                        .HasDatabaseName("IX_AuditRecords_UserName_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("UserName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("UserName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditRecords_Tenant_OccurredAt");

                    b.HasIndex("TenantId", "EventType", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditRecords_Tenant_EventType_OccurredAt");

                    b.HasIndex("TenantId", "EntityName", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditRecords_Tenant_EntityName_OccurredAt");

                    b.HasIndex("EntityKey")
                        .HasDatabaseName("IX_AuditRecords_EntityKey_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EntityKey"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EntityKey"), new[] { "gin_trgm_ops" });

                    b.ToTable("AuditRecords", "audit");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });
#pragma warning restore 612, 618
        }
    }
}
