<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Parties</RootNamespace>
		<AssemblyName>FSH.Modules.Parties</AssemblyName>
		<PackageId>FullStackHero.Modules.Parties</PackageId>
		<NoWarn>$(NoWarn);CA1031;CA1812;CA1859;S3267;CA1308;CA1062;S1144;CA1873</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
		<ProjectReference Include="..\Modules.Parties.Contracts\Modules.Parties.Contracts.csproj" />
	</ItemGroup>

</Project>
