// <auto-generated />
using System;
using FSH.Modules.Parties.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Starter.Migrations.PostgreSQL.Parties
{
    [DbContext(typeof(PartiesDbContext))]
    [Migration("20260616060820_Parties_V2_ParentPartyId")]
    partial class Parties_V2_ParentPartyId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parties")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.Parties.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActividadEconomicaCiiuCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CreditBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("CreditCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CreditDaysCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FiscalResponsibilities")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("GenderCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("HasCredit")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdentificationTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobalSupplier")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("LeadScore")
                        .HasColumnType("integer");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MaritalStatusCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MarketingType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ParentPartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TaxRegimeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerificationDigit")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LegalName");

                    b.HasIndex("ParentPartyId");

                    b.HasIndex("Roles");

                    b.HasIndex("TenantId", "ParentPartyId")
                        .HasDatabaseName("ix_parties_parent");

                    b.HasIndex("TenantId", "IdentificationTypeCode", "IdentificationNumber")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Parties", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barrio")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Line")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("MunicipalityCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("NormalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedLine")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyAddresses", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelTypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyChannels", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Cell")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContactTypeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FullName")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("GenderCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdentificationTypeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MaritalStatusCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PositionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProfessionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyContacts", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("UserId");

                    b.ToTable("PartyTeamMembers", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Credit.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AprobadoPor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("CupoAsignado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CustomerProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiasCredito")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("FechaAprobacion")
                        .HasColumnType("date");

                    b.Property<Guid?>("FormaPagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MonedaId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProfileId");

                    b.ToTable("CreditAccounts", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Credit.CreditMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreditAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentoReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("SaldoResultante")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreditAccountId", "FechaUtc")
                        .HasDatabaseName("ix_creditmov_account");

                    b.ToTable("CreditMovements", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.PartyCiiuActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CiiuCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_ciiu_principal")
                        .HasFilter("\"IsPrincipal\" = TRUE");

                    b.ToTable("PartyCiiuActivities", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.PartyHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaLiberacion")
                        .HasColumnType("date");

                    b.Property<short>("HoldType")
                        .HasColumnType("smallint");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId", "HoldType")
                        .HasDatabaseName("ix_holds_active")
                        .HasFilter("\"EstaActivo\" = TRUE");

                    b.ToTable("PartyHolds", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.ContactProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("ContactFunction")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsCommercialContact")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsibleUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactProfiles_PartyId1");

                    b.HasIndex("PartyId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactProfiles_PartyId");

                    b.ToTable("ContactProfiles", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AllowDiscount")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClassificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultBranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultSalespersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MarketingSourceId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxDiscountPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WithholdingRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerProfiles_PartyId1");

                    b.HasIndex("PartyId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerProfiles_PartyId");

                    b.ToTable("CustomerProfiles", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.EmployeeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCollector")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSalesperson")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ManagerPartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_EmployeeProfiles_PartyId1");

                    b.HasIndex("PartyId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_EmployeeProfiles_PartyId");

                    b.ToTable("EmployeeProfiles", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.PartnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SharePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_PartnerProfiles_PartyId1");

                    b.HasIndex("PartyId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_PartnerProfiles_PartyId");

                    b.ToTable("PartnerProfiles", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.SupplierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClassificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultBankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultPriceListId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDropshipping")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WithholdingRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_SupplierProfiles_PartyId1");

                    b.HasIndex("PartyId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_SupplierProfiles_PartyId");

                    b.ToTable("SupplierProfiles", "parties");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.Party", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithMany()
                        .HasForeignKey("ParentPartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("FSH.Modules.Parties.Domain.V2.FiscalData", "FiscalData", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AgenteRetencionICA")
                                .HasColumnType("boolean")
                                .HasColumnName("FiscalData_AgenteRetencionICA");

                            b1.Property<bool>("AgenteRetencionIVA")
                                .HasColumnType("boolean")
                                .HasColumnName("FiscalData_AgenteRetencionIVA");

                            b1.Property<bool>("Autorretenedor")
                                .HasColumnType("boolean")
                                .HasColumnName("FiscalData_Autorretenedor");

                            b1.Property<bool>("FlagPEP")
                                .HasColumnType("boolean")
                                .HasColumnName("FiscalData_FlagPEP");

                            b1.Property<string>("FormaJuridica")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("FiscalData_FormaJuridica");

                            b1.Property<bool>("GranContribuyente")
                                .HasColumnType("boolean")
                                .HasColumnName("FiscalData_GranContribuyente");

                            b1.Property<bool>("ObligadoLlevarContabilidad")
                                .HasColumnType("boolean")
                                .HasColumnName("FiscalData_ObligadoLlevarContabilidad");

                            b1.Property<short?>("RegimenTributario")
                                .HasColumnType("smallint")
                                .HasColumnName("FiscalData_RegimenTributario");

                            b1.Property<short?>("ResponsabilidadIVA")
                                .HasColumnType("smallint")
                                .HasColumnName("FiscalData_ResponsabilidadIVA");

                            b1.Property<string>("ResponsabilidadesFiscales")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("FiscalData_ResponsabilidadesFiscales");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties", "parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("FiscalData");
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyAddress", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyChannel", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithMany("Channels")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyContact", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithMany("Contacts")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.PartyTeamMember", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithMany("Team")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Credit.CreditAccount", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.V2.Profiles.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Credit.CreditMovement", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.V2.Credit.CreditAccount", null)
                        .WithMany("Movements")
                        .HasForeignKey("CreditAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.PartyCiiuActivity", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithMany("CiiuActivities")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.ContactProfile", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithOne("ContactProfile")
                        .HasForeignKey("FSH.Modules.Parties.Domain.V2.Profiles.ContactProfile", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.CustomerProfile", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithOne("CustomerProfile")
                        .HasForeignKey("FSH.Modules.Parties.Domain.V2.Profiles.CustomerProfile", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.EmployeeProfile", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("FSH.Modules.Parties.Domain.V2.Profiles.EmployeeProfile", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.PartnerProfile", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithOne("PartnerProfile")
                        .HasForeignKey("FSH.Modules.Parties.Domain.V2.Profiles.PartnerProfile", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Profiles.SupplierProfile", b =>
                {
                    b.HasOne("FSH.Modules.Parties.Domain.Party", null)
                        .WithOne("SupplierProfile")
                        .HasForeignKey("FSH.Modules.Parties.Domain.V2.Profiles.SupplierProfile", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FSH.Modules.Parties.Domain.V2.Profiles.PaymentTerms", "PaymentTerms", b1 =>
                        {
                            b1.Property<Guid>("SupplierProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DiasCredito")
                                .HasColumnType("integer")
                                .HasColumnName("PaymentTerms_DiasCredito");

                            b1.Property<Guid?>("FormaPagoId")
                                .HasColumnType("uuid")
                                .HasColumnName("PaymentTerms_FormaPagoId");

                            b1.HasKey("SupplierProfileId");

                            b1.ToTable("SupplierProfiles", "parties");

                            b1.WithOwner()
                                .HasForeignKey("SupplierProfileId");
                        });

                    b.Navigation("PaymentTerms")
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.Party", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Channels");

                    b.Navigation("CiiuActivities");

                    b.Navigation("ContactProfile");

                    b.Navigation("Contacts");

                    b.Navigation("CustomerProfile");

                    b.Navigation("EmployeeProfile");

                    b.Navigation("PartnerProfile");

                    b.Navigation("SupplierProfile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FSH.Modules.Parties.Domain.V2.Credit.CreditAccount", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
